name: Build and Push Containers

on:
  push:
    branches:
      - main
    paths:
      - 'images/*/Containerfile'
      - 'images/*/VERSION'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          for containerfile in $(find images -name '*Containerfile'); do
            dir=$(dirname "$containerfile")
            image_name=$(basename "$dir")
            version="latest"
            if [ -f "$dir/VERSION" ]; then
              version=$(cat "$dir/VERSION")
            else
              version="${{ github.sha }}"
            fi
            if [ -f "$dir/argfile.conf" ]; then
              :
            else
              touch "$dir/argfile.conf"
            fi
            cmd=(
              'docker buildx build --push'
              "--file $containerfile"
              "--tag "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:${version}""
              "--tag "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:latest""
              "--cache-from type=registry,ref=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:buildcache"
              "--cache-to type=registry,ref=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:buildcache,mode=max"
            )
            for ba in $(cat "$dir/argfile.conf"); do
              cmd+=('--build-arg' "$ba")
            done
            cmd+=("$dir")
            eval "${cmd[@]}"
          done
